### ISSUE TITLE
Ignore mixins

### ISSUE THREAD

**Issue by matheusazzi** [leroy-merlin-br/boreal#5]
Precisamos que o boreal ignore `mixins`, por exemplo:

``` scss
@each $sprite in $sprites {
    $sprite-name: nth($sprite, 10);
    .icon-#{$sprite-name} {
        @extend %icon;
        @include retina-sprite($sprite);
    }
  }
```

No caso acima ele vai dizer que a classe `.icon-` não está sendo utilizada.

---

Com isso também surge uma dúvida se não deveríamos utilizar o `boreal` num arquivo css buildado.
